# Generated by Django 3.1.4 on 2023-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0003_auto_20230119_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minicar',
            name='color_b',
        ),
        migrations.RemoveField(
            model_name='minicar',
            name='color_g',
        ),
        migrations.RemoveField(
            model_name='minicar',
            name='color_r',
        ),
        migrations.AddField(
            model_name='minicar',
            name='color',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='minicar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
