# Generated by Django 3.1.4 on 2023-01-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minicar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(default=0, null=True)),
                ('battery', models.IntegerField(default=0, null=True)),
                ('color_r', models.CharField(max_length=20, null=True)),
                ('color_g', models.CharField(max_length=20, null=True)),
                ('color_b', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omorobot.user')),
            ],
        ),
    ]
