# Generated by Django 4.1.5 on 2023-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0013_alter_minicar_battery_alter_minicar_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='mycar',
            name='mycar_battery',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Minicar',
        ),
    ]
