# Generated by Django 4.1.5 on 2023-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0014_remove_user_name_alter_mycar_mycar_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_battery',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
