# Generated by Django 4.1.5 on 2023-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0015_alter_model_model_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_battery',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='mycar_battery',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
