# Generated by Django 4.1.5 on 2023-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0016_alter_model_model_battery_alter_mycar_mycar_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
