# Generated by Django 3.1.4 on 2023-01-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0002_minicar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorobot.user'),
        ),
    ]
