# Generated by Django 3.1.4 on 2023-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0004_auto_20230119_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicar',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
