# Generated by Django 3.1.4 on 2023-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorobot', '0005_minicar_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicar',
            name='month',
            field=models.CharField(default='x', max_length=20, null=True),
        ),
    ]
